layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://amauryortega.dev
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://cdn.worldvectorlogo.com/logos/docker.svg

  - name: Arch Linux
    web_url: https://www.archlinux.org
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Archlinux-vert-dark.svg/1280px-Archlinux-vert-dark.svg.png
    
  - name: CI/CD (GitLab Runner)
    web_url: https://about.gitlab.com/product/continuous-integration
    image_url: https://about.gitlab.com/images/ci/gitlab-ci-cd-logo_2x.png
